In [9]:
#FUNCTIONS AND AXIS
#sum fonksiyonu,toplanmış değerlerin toplamını döndüren bir Python fonksiyonudur.
import numpy as np
a= np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a)
#aşağıdaki satırla hepsini toplar
print(a.sum())
print(a.sum(axis=None))
#aşağıdaki satırla ayrı ayrı toplar.
print(a.sum(axis=1))
#mean fonksiyonu ortalamayı bulur.
print(a.mean())
print(a.mean(axis=1))
#std fonksiyonu veri grubunun, aritmetik ortalamaya göre standart sapmasını gösterir.
print(a.std())
print(a.min())
print(a.max())


[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
210
210
[ 70 140]
15.0
[10. 20.]
5.385164807134504
7
23


In [11]:
#DATATYPES
#verilerin veri tiplerrini görmek için .dtype kullanılır.
x = np.array([1.0,2.0])
print(x.dtype)
#veri tipi değiştirilebilir;
y= np.array([1.0,2.0], dtype=np.int32)
print(y.dtype)

float64
int32


In [16]:
#COPYING
#Eğer direkt arrayleri a=b şeklinde eşleştirirsek bdeki değişiklik a yı da değiştirir.
#Ancak copy kullanırsak sonradan oluşturulan arrayde bir değişiklik oldugunda asıl array değişmez. 
a1= np.array([1,2,3])
b1=a1.copy()
b1[0] =42
print (b1)
print(a1)
#eğer copy yazmayıp direkt eşitleseydik a nın çıktısı da bniniki gibi olurdu

[42  2  3]
[1 2 3]


In [17]:
#GENERATING ARRAYS
#zeros ones ve full ile istenilen bpyutlarda array oluşturulabilir;
a2= np.zeros((2,3))
print(a2)

a3=np.ones((2,3))
print(a3)

a4=np.full((2,3),5.0)
print(a4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [22]:
#eye metodu ile köşegenler ötelenebilir.
a5= np.eye(5,k=-1)
print(a5)
#burada k ya -1 vererek bir satır geriye öteledim 3 olsaydı 3 satır ileri ötelenirdi.

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [24]:
#arange ile istenilen aralıkta array oluşturulabilir
a6=np.arange(20)
print(a6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [25]:
#aşağıdaki satırla 0 ve 20 de dahil olmak üzere aralarındaki sayıyı eşit bölerek 10 elemanlı bir array oluşturdum
a7=np.linspace(0,20,10)
print(a7)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
