In [31]:
#INSTALLATION AND BASICS
import numpy as np
sayilar=np.array([1,2,3,4,5])
print (sayilar)

[1 2 3 4 5]


In [4]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print(a.shape)
#şeklini verir
print(a.size)
#eleman sayısını verir.
print(a.dtype)
#veri tipini verir.
print(a.ndim)
#kac boyutlu oldugunu gösterir.
print(a.itemsize)
print(a[1])
print(a[1,1])
print(a[:,2])
print(a[:,1]) 
print(a[0:3,1])


(3, 3)
9
int32
2
4
[4 5 6]
5
[3 6 9]
[2 5 8]
[2 5 8]


In [32]:
b=a*np.array([2,0,2])
#üstteki satırla anın her elemanı yeni arraydaki sayı ile çarpılıp b matrisini oluşturacaktır.
print(b)

[10  0 14]


In [30]:
#ARRAY VS LIST
#array ve list arasındaki farklar;
#append ile listeye eleman eklenebillirken arraye eklenemez.
#+ işaretiyle listeye eleman eklenebilirken arraye eklenemez.
l=[1,2,3]
a=np.array([1,2,3])
l= l+[4]
a= a+ np.array([4])
print(l)
print(a)

[1, 2, 3, 4]
[5 6 7]


In [34]:
#ayrıca *2 işaretinde liste iki kere aynı şekilde yazılırken arraylerde elemanlar 2 ile çarpılır.
l=l*2
print(l)

a=a*2
print(a)
#aynı zamanda log,sqrt vb. matematiksel operatörler arraylerle kolaylıkla kullanılabilir.

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[20 24 28]


In [38]:
#DOT PRODUCT
l1=[1,2,3]
l2=[4,5,6]
a1= np.array(l1)
a2=np.array(l2)
dot=0
for i in range(len(l1)):
    dot+=l1[i]* l2[i]
print(dot)
#aşağıdaki 2 satır da aynı çıktıyı verecek. dot ile daha hızlı ve daha az satır kullanılabilir.
dot= np.dot(a1,a2)
print(dot)
#aşağıdaki 3 satır ile de aynı çıktıyı elde edebiliriz.
sum1 =a1*a2
dot =np.sum(sum1)
print(dot)
#yine aşağıdaki satırlar ile de aynı çıktıyı elde edebilirz.
dot= a1@ a2
print(dot)


32
32
32
32


In [43]:
#MULTIDIMENSIONAL(ND) ARRAYS 
import numpy as np
a3=np.array([[1,2,6],[3,4,8]])
print(a3)
print(a3.shape)

print(a3[0][1])
print(a3[0,1])

[[1 2 6]
 [3 4 8]]
(2, 3)
2
2


In [48]:
# bazı parametrelerle arraylerin tersini çevirebilir, köşegenlerini yazdırabilir, determinantını hesaplayabiliriz.
import numpy as np
a4=np.array([[1,2],[3,4]])
print(a4)
print(np.linalg.inv(a4))
print(np.linalg.det(a4))
print(np.diag(a4))
c=np.diag(a4)
print(c)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[1 4]
[1 4]
