In [8]:
#INDEXING/SLICING/BOOLEAN INDEXING
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
# indeksleri iyice anlayabilmek iiçin birkaç örnek;
b=a[0,1]
print(b)

c=a[0,:]
print(c)

d=a[:,:]
print(d)

e=a[-1,-1]
print(e)

[[1 2]
 [3 4]]
2
[1 2]
[[1 2]
 [3 4]]
4


In [13]:
#boolean işemleri
a1= np.array([[1,2],[3,4],[5,6]])
bool_idx=a1<=2
print(bool_idx)
bool_idx2= a1>2
print(a1[bool_idx2])

[[ True  True]
 [False False]
 [False False]]
[3 4 5 6]


In [15]:
#aşağıdaki satırlardaki where metodu ile nerede parantez içindeki durum sağlanmazsa oraya o durumdaki elemanlar yerine belirtilen elemanlar konur.
b1= np.where(a1>2, a1,-1)
print(b1)
#Burada 1 ve 2, 2 den büyük olmadıklarından parantez içinde belirtildiği gibi yerlerine -1 konur.

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [23]:
#RESHAPING
#arange ile belirlenen aralıklardaki sayılardan array oluşturulur.
#reshape ile eleman sayısının uyumlu olma şartıyla array yeniden şekillendirilebilir.
a2= np.arange(1,7)
print(a2)
print(a2.shape)
b2=a2.reshape((2,3))
print(b2)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]


In [32]:
#CONCATENATION
#iki arrayi birleştirmenin birkac yöntemi vardir. concatenate yöntemi;
a4=np.array([[1,2],[3,4]])
print(a4)
b4=np.array([[5,6]])
c4=np.concatenate((a4,b4))
print(c4)
#axisle farklı şekilde de birleştirilebilir.*axis=eksen*
c5=np.concatenate((a4,b4), axis=None)
print(c5)
#hstack ile iki arrayi birleştirme;
a5=np.array([1,2,3,4])
b5=np.array([5,6,7,8])
c6=np.hstack((a5,b5))
print(c6)
#vstack ile iki arrayi birleştirme;
c7=np.vstack((a5,b5))
print(c7)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [33]:
#BROADCASTING
#+ operstörü ile arrayler matematiksel olarak toplanabilir;
x =np.array([[1,2,3],[4,5,6],[1,2,3], [4,5,6]])
a10 = np.array([1,0,1])
y =x+a10
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]
